version: '3'

services:
   server:
     depends_on:
       - mysqldb
     build: .
     ports:
       - 9090:8080
     #restart: always     
   mysqldb:
     image: mysql:5.7
     #restart: always
     ports:
       - 3360:3360
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: expensetracker
       MYSQL_USER: manoj
       MYSQL_PASSWORD: kingfisher